version: '3'

volumes:
  postgres_data:

networks:
  accounting-network:

services:
  nuxt:
    build: ./client
    container_name: accounting-ui
    restart: always
    ports:
      - "0.0.0.0:3333:3333"
    command: npm run start
    networks: 
      - accounting-network

  # nginx:
  #   image: nginx:1.13
  #   container_name: accounting-ui-nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx:/etc/nginx/conf.d
  #   depends_on:
  #     - nuxt
  #   networks: 
  #     - accounting-network

  rest:
    build: ./restApi
    env_file: ./restApi/.env
    restart: always
    container_name: accounting-rest-api-server
    command: python /src/manage.py runserver 0.0.0.0:8091
    volumes:
      - .:/app
    ports:
      - 0.0.0.0:8091:8091
    networks: 
      accounting-network:
        aliases:
          - rest-api
    depends_on:
      - db
    
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks: 
      accounting-network:
        aliases:
          - database
    # ports:
    #   - 5432:5432
  
  graphql:
    build: ./server
    restart: always
    container_name: accounting-graphql-server
    env_file: ./server/.env
    command: npm run start
    volumes:
      - .:/app
    ports:
      - 0.0.0.0:4002:4002
    networks: 
      accounting-network:
        aliases:
          - graphql-server