# Generated by Django 2.2.3 on 2019-07-31 06:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_remove_transaction_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата проведения операции'),
        ),
    ]
