# Generated by Django 2.2.3 on 2019-09-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_auto_20190818_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='branch',
            new_name='transaction_object',
        ),
        migrations.AddField(
            model_name='transaction',
            name='segment',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Категория'),
        ),
    ]
