# Generated by Django 2.2.3 on 2019-11-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_auto_20190930_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='total_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, verbose_name='Баланс/Сальдо'),
        ),
        migrations.AddField(
            model_name='account',
            name='total_consumption',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, verbose_name='Расход'),
        ),
        migrations.AddField(
            model_name='account',
            name='total_profit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, verbose_name='Приход'),
        ),
        migrations.AddField(
            model_name='account',
            name='transaction_types',
            field=models.ManyToManyField(blank=True, related_name='used_transactions_types_by_account', to='accounting.TransactionType', verbose_name='Сущестующие типы транзакции'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, verbose_name='Баланс/Сальдо'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='consumption',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, verbose_name='Расход'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, verbose_name='Приход'),
        ),
    ]
