# Generated by Django 2.2.3 on 2019-11-02 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_auto_20191101_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='transaction_types',
            new_name='transactions_types',
        ),
    ]
